### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Page-**
Change-type: patch

### CODE REVIEW

**Comment by Page-** [comment]
@balena-ci I self-certify!

**Review by ghost — APPROVED** [review]

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@Page- Are these circle tests still running? The checks might need to be removed from this repos settings

**Comment by Page-** [comment]
@LucianBuzzo circleci only runs on followed projects and I'm guessing with repo move or someone being removed that there were no followers left - I've just followed so they'll start running again

**Comment by Page-** [comment]
That said the node 6/8 aren't exactly useful so I'll remove them

**Pull request merged**
