### PR TITLE
Ensure the `name` property in the `Function` interface is readonly.

### PR DESCRIPTION
**Pull request by hedss**
Ensures ES6 TypeScript projects build cleanly.

Connects-To: #3

Change-Type: patch

### CODE REVIEW

**Comment by hedss** [comment]
I'm aware there's an outstanding issue on name, as it is in #2.

**Comment by Page-** [comment]
add to whitelist

**Review by Page- — APPROVED** [review]

**Review by Page- — CHANGES_REQUESTED** [review]
Can you add a changelog entry please

**Comment by hedss** [comment]
Sorry, yes. Too used to everything being on VersionBot! I could actually add this to VB, and update the PR with a modified changelog, if you'd like?

**Comment by hedss** [comment]
@Page- I've updated the `CHANGELOG.md` and `package.json` manually (v1.0.1) with style changes in `CHANGELOG.md` to mean that post-merge, it just needs the tag adding and then it can under VB control. Is that OK?

**Review by Page- — APPROVED** [review]

**Pull request merged**
