### PR TITLE
Delete .github directory

### PR DESCRIPTION
**Pull request by dfunckt**
Change-type: patch

### CODE REVIEW

**Comment by dfunckt** [comment]
@balena-ci I self-certify!

**Comment by dfunckt** [comment]
What? Why?

```
10 passing (32ms)
  2 failing

  1) typescript
       Standard try/catch
         constructor.name:
     AssertionError: expected [MyError] to have nested property 'constructor.name'
      at Context.it (test/typescript.ts:44:29)

  2) coffeescript
       Standard try/catch
         constructor.name:
     AssertionError: expected [MyError] to have nested property 'constructor.name'
      at Context.<anonymous> (test/coffeescript.coffee:45:41)



npm ERR! Test failed.  See above for more details.
```

**Comment by vipulgupta2048** [comment]
@balena-ci retest

**Comment by dfunckt** [comment]
@balena-ci rebase

**Comment by dfunckt** [comment]
@balena-ci retest

**Review by Page- — APPROVED** [review]

**Comment by dfunckt** [comment]
@balena-ci retest

**Pull request closed without merging**
